version: "3.1"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
      - POSTGRES_DB=test_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql