version: "3"
services:
  postgres:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
      - POSTGRES_DB=test_db
    volumes:
      - ./data/db.sql:/docker-entrypoint-initdb.d/init.sql
